<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.3" />
        <PackageReference Include="Avalonia.Desktop" Version="11.2.1"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.1"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.1"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.2.1">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="Simplecto.Avalonia.RichTextBox" Version="1.0.12" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Resources\Carteles\" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="View\MainView.axaml.cs">
        <DependentUpon>MainWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <None Remove="Resources\Carteles\Spiderman.jpg" />
      <AvaloniaResource Include="Resources\Carteles\Spiderman.jpg" />
      <None Remove="Resources\fondo.png" />
      <AvaloniaResource Include="Resources\fondo.png" />
      <None Remove="Resources\filmoteca.png" />
      <AvaloniaResource Include="Resources\filmoteca.png" />
      <None Remove="Resources\rollo.ico" />
      <AvaloniaResource Include="Resources\rollo.ico" />
      <None Remove="Resources\Carteles\default.jpg" />
      <AvaloniaResource Include="Resources\Carteles\default.jpg" />
    </ItemGroup>
</Project>
